Fixes #408
oughtinc/ergo pull request #417
Opened 2020-09-16 18:13 UTC by NixGD

Fixes a read-only error resulting from data being an immutable `jax.np` array instead of a normal numpy array.  Also adds two tests that ensure `show_prediction()` runs without errors (although it does not test the accuracy of the graphs produced).

2020-09-22 03:43 UTC, brachbach requested changes
Thanks for catching and fixing this, @NixGD!

Had a couple comments to address before we merge

2020-09-22 03:43 UTC, brachbach commented on ergo/platforms/metaculus/question/continuous.py
> +                    df[col] = onp.array(self.scale.normalize_points(samples[col]))
@NixGD could you add a comment in the code here about what exactly this fixes?

(both for my benefit reviewing the PR, and for the benefit of future code maintainers)

2020-09-22 03:43 UTC, brachbach commented on tests/test_metaculus.py
> +def test_show_prediction_with_fitted(
I'm not a big fan of just testing that the code runs without erroring (as opposed to actually testing that it does the desired thing). I think we should just get rid of these tests

But if you feel like we should keep them, add docstrings explaining why

2020-09-22 03:44 UTC, brachbach commented on tests/test_metaculus.py
> +def test_show_prediction_with_fitted(
(TBC I am grateful that you included these for the sake of this PR, so we can see that #408 is indeed fixed, but I don't think it's worth keeping them)

2020-09-22 20:17 UTC, NixGD commented
Changes made as requested!  I don't understand the internals of pandas well enough to descirbe the problem in full detail; I can't find good documentation on what can and cannot be done to immutable data in pandas dataframes.

2020-09-29 02:00 UTC, brachbach approved these changes
Thanks for making the changes! I'll merge

2020-09-29 02:00 UTC, merged